VrPark.Web/ViewModels/ParkItemViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VrPark.Web.ViewModels
{
    public class ParkItemViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resources.Resources), ErrorMessageResourceName = "ERR_Required")]
        [Display(Name = "ParkItemCategory", ResourceType = typeof(Resources.Resources))]
        public int ParkItemCategoryId { get; set; }

        public ParkItemCategoryViewModel ParkItemCategory { get; set; }

        public String Code { get; set; }

        public String Name { get; set; }

        public decimal Latitude { get; set; }

        public decimal Longitude { get; set; }

        public String Description { get; set; }

        public String AdditionalInformation { get; set; }

        public virtual ICollection<ParkItemMediaViewModel> ParkItemMedia { get; set; }
    }
}

VrPark.Web/Controllers/ParkItemsController.cs
using AutoMapper;
using Ninject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VrPark.Database.Models;
using System.Net;
using NLog;
using VrPark.Web.ViewModels;
using VrPark.Services;
using VrPark.Web.Helpers;

namespace VrPark.Web.Controllers
{
    public class ParkItemsController : BaseController
    {
        [Inject]
        public ParkItemService ParkItemService { private get; set; }

        [Inject]
        public ParkItemCategoryService ParkItemCategoryService { private get; set; }

        private MapHelper<ParkItem, ParkItemViewModel> mapper;

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            mapper = new MapHelper<ParkItem, ParkItemViewModel>();
        }

        // GET: ParkItems
        public ActionResult Index()
        {
            var parkItems = ParkItemService.GetAll().ToList();
            return View(mapper.Map(parkItems));
        }

        // GET: ParkItems/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Create = "true";
            ViewBag.ParkItemCategoryId = new SelectList(ParkItemCategoryService.GetAll(), "Id", "Code");
            return View();
        }

        // POST: ParkItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ParkItemViewModel parkItemViewModel)
        {
            var parkItem = Mapper.Map<ParkItemViewModel, ParkItem>(parkItemViewModel);

            if (ModelState.IsValid)
            {
                try
                {
                    ParkItemService.Add(parkItem);
                    ParkItemService.Save();

                    // sweet alert for successful save

                    TempData["Toastr"] = new Toastr
                    {
                        Title = Resources.Resources.ParkItems,
                        Message = Resources.Resources.EntrySaveSuccess,
                        Severity = "success"
                    };

                    logger.Info("New park item created with id: {0}", parkItem.Id);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // sweet alert for error save
                    logger.Error(ex, "Error in saving a new park item in db");
                    TempData["Toastr"] = new Toastr
                    {
                        Title = Resources.Resources.ParkItems,
                        Message = Resources.Resources.EntrySaveError,
                        Severity = "error"
                    };
                }
            }

            return View(parkItemViewModel);
        }

        // GET: ParkItems/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkItem parkItem = ParkItemService.FindById(id.Value);

            if (parkItem == null)
            {
                return HttpNotFound();
            }

            return View(Mapper.Map<ParkItem, ParkItemViewModel>(parkItem));
        }

        // POST: ParkItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ParkItemViewModel parkItemViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var parkItem = ParkItemService.FindBy(p => p.Id == parkItemViewModel.Id).Single();
                    parkItem = Mapper.Map<ParkItemViewModel, ParkItem>(parkItemViewModel);

                    var parkItemCategory = ParkItemCategoryService.FindBy(pc => pc.Id == parkItem.ParkItemCategoryId).FirstOrDefault();
                    parkItem.ParkItemCategory = parkItemCategory;

                    ParkItemService.EditAndSave(parkItem);
                    TempData["Toastr"] = new Toastr
                    {
                        Title = Resources.Resources.ParkItems,
                        Message = Resources.Resources.EntrySaveSuccess,
                        Severity = "success"
                    };

                    logger.Info("Park item with id: {0} edited successfully", parkItem.Id);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // Error of unique account name
                    if (ex.InnerException != null && ex.InnerException.InnerException != null && ((System.Data.SqlClient.SqlException)ex.InnerException.InnerException).Number == 2601)
                    {
                        TempData["Toastr"] = new Toastr
                        {
                            Title = Resources.Resources.ParkItems,
                            Message = Resources.Resources.ParkItemDuplicateName,
                            Severity = "error"
                        };
                    }
                    else
                    {
                        TempData["Toastr"] = new Toastr
                        {
                            Title = Resources.Resources.ParkItems,
                            Message = Resources.Resources.EntrySaveError,
                            Severity = "error"
                        };
                    }

                    logger.Error(ex, "Error in editing an existing park with id: {0}", parkItemViewModel.Id);
                }
            }

            return View(parkItemViewModel);
        }

        // POST: ParkItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var parkItem = ParkItemService.FindBy(pit => pit.Id == id).Single();

            if (parkItem == null)
            {
                return HttpNotFound();
            }

            try
            {
                ParkItemService.Delete(parkItem);
                ParkItemService.Save();

                TempData["Toastr"] = new Toastr
                {
                    Title = Resources.Resources.ParkItems,
                    Message = Resources.Resources.EntryDeleteSuccess,
                    Severity = "success"
                };

                logger.Info("Successful deleting of an existing park with id: {0}", parkItem.Id);
            }
            catch (Exception ex)
            {
                TempData["Toastr"] = new Toastr
                {
                    Title = Resources.Resources.ParkItems,
                    Message = Resources.Resources.EntryDeleteError,
                    Severity = "error"
                };

                logger.Error(ex, "Error in deleting an existing park with id: {0}", parkItem.Id);
            }

            return RedirectToAction("Index");
        }
    }
}

VrPark.Web/Views/ParkItems/Create.cshtml
@model VrPark.Web.ViewModels.ParkItemViewModel
@using VrPark.Resources

@{
    ViewBag.Title = Resources.ParkItems + " / " + Resources.Create;
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Watt and Volt</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">@Resources.Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "ParkItems", "Index")">@Resources.ParkItems</a>
            </li>
            <li class="active">
                <strong>@Resources.Create</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-plus-circle text-wv"></i> @Resources.CreateParkItem</h5>
                </div>
                @RenderPage("_formParkItem.cshtml")
            </div>
        </div>
    </div>
</div>

@section Scripts {

    @* javascript *@
    @Scripts.Render("~/bundles/jqueryval")
}

VrPark.Web/Views/ParkItems/Edit.cshtml
@model VrPark.Web.ViewModels.ParkItemViewModel
@using VrPark.Resources

@{
    ViewBag.Title = Resources.ParkItems + " / " + Resources.Edit;
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Watt and Volt</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">@Resources.Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "ParkItems", "Index")">@Resources.ParkItems</a>
            </li>
            <li class="active">
                <strong>@Resources.Edit</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5><i class="fa fa-pencil text-wv"></i> @Resources.EditParkItem</h5>
                </div>
                @RenderPage("_formParkItem.cshtml")
            </div>
        </div>
    </div>
</div>


@section Scripts {

    @* javascript *@
    @Scripts.Render("~/bundles/jqueryval")
}

VrPark.Web/Views/ParkItems/Index.cshtml
@model IEnumerable<VrPark.Web.ViewModels.ParkItemViewModel>
@using VrPark.Resources

@{
    ViewBag.Title = Resources.ParkItems + " / " + Resources.Search;
}


<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Watt and Volt</h2>
        <ol class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Home")">@Resources.Home</a>
            </li>
            <li>
                <a href="@Url.Action("Index", "ParkItems")">@Resources.ParkItems</a>
            </li>
            <li class="active">
                <strong>@Resources.List</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
    <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5><i class="fa fa-tachometer text-wv"></i> @Resources.ParkItems</h5>
            <div class="ibox-tools">
                <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                </a>
                <a class="close-link">
                    <i class="fa fa-times"></i>
                </a>
            </div>
        </div>
        <div class="ibox-content">
            <div class="table-responsive">
                <div class="m-b">
                    <a href="@Url.Action("Create", "ParkItems")" class="btn btn-sm btn-outline btn-info"><b>@Resources.NewParkItem</b></a>
                </div>
                <table id="parkItemsTable" class="table table-striped table-hover dataTable">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.ParkItemCategory.Code)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Code)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Latitude)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Longitude)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.AdditionalInformation)
                            </th>
                            <th width="80" align="right"></th>
                        </tr>
                    </thead>

                    <tbody>
                        @if (Model.Count() > 0)
                        {
                            foreach (var item in Model)
                            {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ParkItemCategory.Code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Code)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Latitude)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Longitude)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.AdditionalInformation)
                            </td>
                            @*<td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                            </td>*@

                            <td>
                                <form action="@Url.Action("Delete", "ParkItems", new {id = item.Id})" method="post">
                                    <a class="btn btn-xs btn-primary" href="@Url.Action("Edit", "ParkItems", new { Id = item.Id })">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    @Html.AntiForgeryToken()
                                    <a class="btn btn-xs btn-danger confirm-delete">
                                        <i class="fa fa-remove"></i>
                                    </a>
                                </form>
                            </td>
                        </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="7"><em>@Resources.NoRecords</em></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

        </div>
    </div>
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            var table = $('#parkItemsTable').DataTable({
                dom: "<'row'<'col-sm-4'l><'col-sm-4 text-right'f><'col-sm-4 text-right'B>>" + "<'row'<'col-sm-12'tr>>" + "<'row'<'col-sm-5'i><'col-sm-7'p>>",
                "iDisplayLength": 10,
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                "columnDefs": [
                    { className: "dt-center", targets: "_all" },
                    { sortable: false, className: "dt-right", targets: [7] }
                ],
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
                language: {
                    url: "../Content/plugins/datatables/greek.json"
                },
                initComplete: function () {
                    table.buttons().container().appendTo('#parkItemsTable_wrapper .col-sm-6:eq(0)');

                    // change button color
                    $('#parkItemsTable_wrapper .dt-buttons a.btn-default').removeClass("btn-default").addClass("btn btn-sm btn-outline btn-primary")
                }
            });
        });
    </script>
}

VrPark.Web/Views/ParkItems/_formParkItem.cshtml
@model VrPark.Web.ViewModels.ParkItemViewModel
@using VrPark.Resources

<div class="ibox-content">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ParkItemCategoryId, "ParkItemCategoryId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ParkItemCategoryId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ParkItemCategoryId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.AdditionalInformation, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.AdditionalInformation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AdditionalInformation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2 text-right">
                                <button type="submit" class="btn btn-sm btn-primary" id="ParkItem">
                                    <i class="fa fa-save"></i>&nbsp;&nbsp;@Resources.Save
                                </button>
                                <a href="@Url.Action("Index")" class="btn btn-sm btn-danger">
                                    <i class="fa fa-close"></i>&nbsp;&nbsp;@Resources.Cancel
                                </a>
                            </div>
                        </div>
                

            </div>
            }
        </div>
    </div>
</div>